version: 2

models:
  - name: my_first_dbt_model
    columns:
      - name: id
        data_tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null