Dbt_project_1:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 
      user: 
      password: 
      role: ACCOUNTADMIN
      database: dbt_db
      warehouse: dbt_wh
      schema: dbt_schema
      threads: 4
